name: reelstate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
<<<<<<< HEAD
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
=======
  flutter_localizations:
    sdk: flutter  
>>>>>>> 4e59fd43404a4c203582d461160686c45ad1e05c

  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

<<<<<<< HEAD
=======
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
>>>>>>> 4e59fd43404a4c203582d461160686c45ad1e05c
flutter:
  uses-material-design: true

  assets:
     
    - assets/images/
<<<<<<< HEAD
    - assets/lottie/

=======
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
>>>>>>> 4e59fd43404a4c203582d461160686c45ad1e05c
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
<<<<<<< HEAD

# ---------------- SPLASH CONFIG ----------------
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
=======
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
>>>>>>> 4e59fd43404a4c203582d461160686c45ad1e05c
